### ISSUE TITLE
Upating structure for clearer design

### ISSUE THREAD

**Issue by dortheimer** [imandel/vanity#13]
A clear directory structure is essential for collaboration and release as an open source project.
Here are some suggestions:
- Make vanity a pure JS project. This will allow reusing vanity for various projects. It will have a simple API similar to the python class API.

- [ ] Make a python wrapper to support Jupyter as a separate project. It will have vanity.js as a dependency.
- [ ]  Add python requirements.
- [ ]  Add tests to janity.js.
- [ ]  Add component, views, lib directories to vanity.js and organize the code.
- [ ]  Remove temp code and files.

**Comment by dortheimer** [comment]
@imandel your opinion?

**Comment by imandel** [comment]
I agree that makes sense. It is outside of scope of what I can commit to right now, you're welcome to make a branch/fork and implement these things. A good example might be [ThreeJs](https://threejs.org/) and its [corresponding widget](https://github.com/jupyter-widgets/pythreejs). Even with that reorg I'd probably try to keep the components svelte+typescript. Svelte components are [fully compatible](https://custom-elements-everywhere.com/libraries/svelte/results/results.html) with the [custom elements spec](https://www.webcomponents.org/introduction). Ideally anyone would be able to use just HTML to compose various analysis dashboards.
